// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBUe3OzXIC2zZ3NJkyUjSeNYMxhgeAx77U',
    appId: '1:20001422130:web:02a3296ebe2361efc4f52b',
    messagingSenderId: '20001422130',
    projectId: 'fir-app-f1e5a',
    authDomain: 'fir-app-f1e5a.firebaseapp.com',
    storageBucket: 'fir-app-f1e5a.appspot.com',
    measurementId: 'G-D250F398HJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDUqxpFmumgO1DLMhTZhlSGxKnLdOjk0jo',
    appId: '1:20001422130:android:63a0bb43975909f9c4f52b',
    messagingSenderId: '20001422130',
    projectId: 'fir-app-f1e5a',
    storageBucket: 'fir-app-f1e5a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAA-81Nd4AWlmeJjKsIn5D7G04NLfz3-WI',
    appId: '1:20001422130:ios:cf0129b1ace88d2cc4f52b',
    messagingSenderId: '20001422130',
    projectId: 'fir-app-f1e5a',
    storageBucket: 'fir-app-f1e5a.appspot.com',
    iosBundleId: 'com.example.firebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAA-81Nd4AWlmeJjKsIn5D7G04NLfz3-WI',
    appId: '1:20001422130:ios:af1a4730a0f9ad3bc4f52b',
    messagingSenderId: '20001422130',
    projectId: 'fir-app-f1e5a',
    storageBucket: 'fir-app-f1e5a.appspot.com',
    iosBundleId: 'com.example.firebase.RunnerTests',
  );
}
